apiVersion: v1
kind: ConfigMap
metadata:
  name: cluster-monitoring-config
  namespace: openshift-monitoring
data:
  config.yaml: |
    enableUserWorkload: false
    prometheusOperator:
      nodeSelector:
        node-role.kubernetes.io/router: ""
      tolerations:
      - key: "router"
        operator: "Equal"
        value: "router"
        effect: "NoSchedule"

    prometheusK8s:
      retention: 7d
      nodeSelector:
        node-role.kubernetes.io/router: ""
      tolerations:
      - key: "router"
        operator: "Equal"
        value: "router"
        effect: "NoSchedule"
      volumeClaimTemplate:
       spec:
         storageClassName: managed-nfs-storage
         volumeMode: Filesystem
         resources:
           requests:
             storage: 100Gi

    alertmanagerMain:
      nodeSelector:
        node-role.kubernetes.io/router: ""
      tolerations:
      - key: "router"
        operator: "Equal"
        value: "router"
        effect: "NoSchedule"
      volumeClaimTemplate:
       spec:
         storageClassName: managed-nfs-storage
         volumeMode: Filesystem
         resources:
           requests:
             storage: 2Gi

    kubeStateMetrics:
      nodeSelector:
        node-role.kubernetes.io/router: ""
      tolerations:
      - key: "router"
        operator: "Equal"
        value: "router"
        effect: "NoSchedule"

    grafana:
      nodeSelector:
        node-role.kubernetes.io/router: ""
      tolerations:
      - key: "router"
        operator: "Equal"
        value: "router"
        effect: "NoSchedule"

    k8sPrometheusAdapter:
      nodeSelector:
        node-role.kubernetes.io/router: ""
      tolerations:
      - key: "router"
        operator: "Equal"
        value: "router"
        effect: "NoSchedule"

    telemeterClient:
      nodeSelector:
        node-role.kubernetes.io/router: ""
      tolerations:
      - key: "router"
        operator: "Equal"
        value: "router"
        effect: "NoSchedule"

    openshiftStateMetrics:
      nodeSelector:
        node-role.kubernetes.io/router: ""
      tolerations:
      - key: "router"
        operator: "Equal"
        value: "router"
        effect: "NoSchedule"

    thanosQuerier:
      nodeSelector:
        node-role.kubernetes.io/router: ""
      tolerations:
      - key: "router"
        operator: "Equal"
        value: "router"
        effect: "NoSchedule"
